FROM mhart/alpine-node:5.6.0

EXPOSE 3000
ENV NODE_ENV qa
ENV DB_NAME qa
ENV DB_HOST mysql
ENV DB_USER qa
ENV DB_PASSWORD qa
RUN mkdir /app
WORKDIR /app

# add package.json and run npm install before adding the rest of the files
# this way, you only run npm install when package.json changes
ADD package.json /app/package.json
RUN npm install

# add the rest of the files
ADD . /app

CMD ["node", "server.js"]
